'use client';

import { useEffect, useMemo, useState } from 'react';
import { API_BASE } from '@/lib/api';

type Shift = {
  platform: string;
  hours_worked: number;
  gross_earned: number;
  platform_deductions: number;
  net_received: number;
  verification_status: string;
};

export default function CertificatePage() {
  const [shifts, setShifts] = useState<Shift[]>([]);
  const [from, setFrom] = useState(new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString().slice(0, 10));
  const [to, setTo] = useState(new Date().toISOString().slice(0, 10));
  const [profile, setProfile] = useState({
    name: 'Worker',
    id: '',
    category: '',
    zone: '',
  });

  useEffect(() => {
    const run = async () => {
      const workerId = localStorage.getItem('fairgig_user_id');
      if (!workerId) return;

      setProfile({
        name: localStorage.getItem('fairgig_user_name') || 'Worker',
        id: localStorage.getItem('fairgig_user_id') || '',
        category: localStorage.getItem('fairgig_category') || '',
        zone: localStorage.getItem('fairgig_city_zone') || '',
      });

      const res = await fetch(`${API_BASE.earnings}/shifts?worker_id=${workerId}&from=${from}&to=${to}`);
      const data = await res.json();
      setShifts(data.filter((s: Shift) => s.verification_status === 'verified'));
    };
    run();
  }, [from, to]);

  const summary = useMemo(() => {
    const byPlatform = new Map<string, { shifts: number; gross: number; deductions: number; net: number }>();
    let totalHours = 0;
    let totalNet = 0;

    for (const s of shifts) {
      const prev = byPlatform.get(s.platform) || { shifts: 0, gross: 0, deductions: 0, net: 0 };
      prev.shifts += 1;
      prev.gross += Number(s.gross_earned);
      prev.deductions += Number(s.platform_deductions);
      prev.net += Number(s.net_received);
      byPlatform.set(s.platform, prev);
      totalHours += Number(s.hours_worked);
      totalNet += Number(s.net_received);
    }

    return {
      rows: Array.from(byPlatform.entries()).map(([platform, data]) => ({ platform, ...data })),
      totalHours,
      totalNet,
      avgHourly: totalHours > 0 ? totalNet / totalHours : 0,
    };
  }, [shifts]);

  return (
    <div className="space-y-4">
      <div className="card no-print flex items-end gap-3 action-buttons">
        <div>
          <label className="mb-1 block text-sm">From</label>
          <input type="date" className="input" value={from} onChange={(e) => setFrom(e.target.value)} />
        </div>
        <div>
          <label className="mb-1 block text-sm">To</label>
          <input type="date" className="input" value={to} onChange={(e) => setTo(e.target.value)} />
        </div>
        <button className="btn" onClick={() => window.print()}>Print Certificate</button>
      </div>

      <div className="certificate-container mx-auto max-w-4xl rounded-lg border border-gray-300 bg-white p-8 shadow">
        <div className="mb-6 border-b pb-4">
          <h1 className="text-3xl font-bold">FairGig</h1>
          <p className="text-sm text-green-700">VERIFIED INCOME CERTIFICATE</p>
        </div>

        <div className="mb-6 grid grid-cols-1 gap-2 text-sm md:grid-cols-2">
          <p>Worker: {profile.name}</p>
          <p>ID: {profile.id}</p>
          <p>Category: {profile.category}</p>
          <p>Zone: {profile.zone}</p>
          <p className="md:col-span-2">Period: {from} to {to}</p>
        </div>

        <table className="mb-6 w-full border text-sm">
          <thead>
            <tr className="border-b bg-gray-50">
              <th className="p-2 text-left">Platform</th>
              <th className="p-2 text-left">Shifts</th>
              <th className="p-2 text-left">Gross</th>
              <th className="p-2 text-left">Deduct</th>
              <th className="p-2 text-left">Net</th>
            </tr>
          </thead>
          <tbody>
            {summary.rows.map((row) => (
              <tr key={row.platform} className="border-b">
                <td className="p-2">{row.platform}</td>
                <td className="p-2">{row.shifts}</td>
                <td className="p-2">Rs. {row.gross.toFixed(0)}</td>
                <td className="p-2">Rs. {row.deductions.toFixed(0)}</td>
                <td className="p-2">Rs. {row.net.toFixed(0)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="space-y-2 border-t pt-4">
          <p className="text-lg font-bold">TOTAL VERIFIED NET INCOME: Rs. {summary.totalNet.toFixed(0)}</p>
          <p>Total Hours: {summary.totalHours.toFixed(1)} hrs | Avg: Rs.{summary.avgHourly.toFixed(0)}/hr</p>
          <p className="text-xs text-gray-500">Generated by FairGig | Not a legal doc</p>
        </div>
      </div>
    </div>
  );
}
